import type {
  Persona,
  Reaction,
  AggregatedResults,
  OptimizedMessage,
} from "./types";

// Sample personas from the 5,000 pool
export const MOCK_PANEL: Persona[] = [
  {
    uuid: "p-001",
    age: 35,
    sex: "Male",
    occupation: "Hotel Manager",
    education_level: "Bachelor's degree",
    marital_status: "Married",
    planning_area: "Montreal",
    province: "Quebec",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Southeast Asian",
    languages_spoken: "French, English",
    housing: "Owner, Apartment",
    cultural_background: "Cambodian-Canadian",
    political_leaning: "Moderate",
    religion: "Christian",
    top_concerns: ["healthcare", "language and culture"],
    commute_mode: "drives",
    estimated_annual_income: 88209,
    income_bracket: "$80K-$100K",
  },
  {
    uuid: "p-002",
    age: 28,
    sex: "Female",
    occupation: "Software Developer",
    education_level: "Bachelor's degree",
    marital_status: "Never married",
    planning_area: "Toronto",
    province: "Ontario",
    immigration_status: "Immigrant",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "South Asian",
    languages_spoken: "English, Hindi",
    housing: "Renter, Condo",
    cultural_background: "Indian-Canadian, first-generation",
    political_leaning: "Centre-left",
    religion: "Hindu",
    top_concerns: ["housing affordability", "cost of living"],
    commute_mode: "public transit",
    estimated_annual_income: 95000,
    income_bracket: "$80K-$100K",
  },
  {
    uuid: "p-003",
    age: 62,
    sex: "Male",
    occupation: "Retired Teacher",
    education_level: "Master's degree",
    marital_status: "Married",
    planning_area: "Victoria",
    province: "British Columbia",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Not a visible minority",
    languages_spoken: "English",
    housing: "Owner, Detached house",
    cultural_background: "British-Canadian, third generation",
    political_leaning: "Centre-left",
    religion: "No religion",
    top_concerns: ["healthcare", "climate change"],
    commute_mode: "walks",
    estimated_annual_income: 52000,
    income_bracket: "$40K-$60K",
  },
  {
    uuid: "p-004",
    age: 41,
    sex: "Female",
    occupation: "Nurse Practitioner",
    education_level: "Master's degree",
    marital_status: "Divorced",
    planning_area: "Calgary",
    province: "Alberta",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Not a visible minority",
    languages_spoken: "English",
    housing: "Owner, Townhouse",
    cultural_background: "Ukrainian-Canadian, prairie roots",
    political_leaning: "Centre-right",
    religion: "Christian",
    top_concerns: ["healthcare", "economy"],
    commute_mode: "drives",
    estimated_annual_income: 110000,
    income_bracket: "$100K-$120K",
  },
  {
    uuid: "p-005",
    age: 23,
    sex: "Female",
    occupation: "University Student",
    education_level: "Some university",
    marital_status: "Never married",
    planning_area: "Halifax",
    province: "Nova Scotia",
    immigration_status: "Canadian-born",
    indigenous_identity: "Mi'kmaq",
    visible_minority: "Not a visible minority",
    languages_spoken: "English",
    housing: "Renter, Apartment",
    cultural_background: "Mi'kmaq, grew up in Eskasoni First Nation",
    political_leaning: "Left",
    religion: "Spiritual",
    top_concerns: ["Indigenous rights", "education", "climate change"],
    commute_mode: "public transit",
    estimated_annual_income: 18000,
    income_bracket: "Under $20K",
  },
  {
    uuid: "p-006",
    age: 55,
    sex: "Male",
    occupation: "Farmer",
    education_level: "High school diploma",
    marital_status: "Married",
    planning_area: "Saskatoon",
    province: "Saskatchewan",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Not a visible minority",
    languages_spoken: "English",
    housing: "Owner, Farm property",
    cultural_background: "German-Canadian, fourth generation",
    political_leaning: "Right",
    religion: "Lutheran",
    top_concerns: ["economy", "agriculture policy"],
    commute_mode: "drives",
    estimated_annual_income: 72000,
    income_bracket: "$60K-$80K",
  },
  {
    uuid: "p-007",
    age: 33,
    sex: "Female",
    occupation: "Marketing Manager",
    education_level: "Bachelor's degree",
    marital_status: "Common-law",
    planning_area: "Ottawa",
    province: "Ontario",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Black",
    languages_spoken: "English, French",
    housing: "Renter, Apartment",
    cultural_background: "Jamaican-Canadian, parents immigrated in the 80s",
    political_leaning: "Centre-left",
    religion: "Christian",
    top_concerns: ["cost of living", "racial equity"],
    commute_mode: "cycles",
    estimated_annual_income: 82000,
    income_bracket: "$80K-$100K",
  },
  {
    uuid: "p-008",
    age: 47,
    sex: "Male",
    occupation: "Oil Field Technician",
    education_level: "College diploma",
    marital_status: "Married",
    planning_area: "Edmonton",
    province: "Alberta",
    immigration_status: "Canadian-born",
    indigenous_identity: "Métis",
    visible_minority: "Not a visible minority",
    languages_spoken: "English",
    housing: "Owner, Detached house",
    cultural_background: "Métis, strong ties to land and resource work",
    political_leaning: "Right",
    religion: "Christian",
    top_concerns: ["economy", "energy sector", "Indigenous rights"],
    commute_mode: "drives",
    estimated_annual_income: 98000,
    income_bracket: "$80K-$100K",
  },
  {
    uuid: "p-009",
    age: 30,
    sex: "Male",
    occupation: "Chef",
    education_level: "College diploma",
    marital_status: "Never married",
    planning_area: "Vancouver",
    province: "British Columbia",
    immigration_status: "Immigrant",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Chinese",
    languages_spoken: "English, Mandarin, Cantonese",
    housing: "Renter, Apartment",
    cultural_background: "Chinese-Canadian, immigrated at age 12",
    political_leaning: "Moderate",
    religion: "No religion",
    top_concerns: ["housing affordability", "cost of living"],
    commute_mode: "public transit",
    estimated_annual_income: 48000,
    income_bracket: "$40K-$60K",
  },
  {
    uuid: "p-010",
    age: 39,
    sex: "Female",
    occupation: "Social Worker",
    education_level: "Master's degree",
    marital_status: "Married",
    planning_area: "Winnipeg",
    province: "Manitoba",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Filipino",
    languages_spoken: "English, Tagalog",
    housing: "Owner, Semi-detached",
    cultural_background: "Filipino-Canadian, tight-knit community in Winnipeg",
    political_leaning: "Centre-left",
    religion: "Catholic",
    top_concerns: ["healthcare", "immigration", "family services"],
    commute_mode: "drives",
    estimated_annual_income: 68000,
    income_bracket: "$60K-$80K",
  },
  {
    uuid: "p-011",
    age: 52,
    sex: "Male",
    occupation: "Fisherman",
    education_level: "High school diploma",
    marital_status: "Married",
    planning_area: "St. John's",
    province: "Newfoundland and Labrador",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Not a visible minority",
    languages_spoken: "English",
    housing: "Owner, Detached house",
    cultural_background: "Irish-Newfoundlander, generations in the fishery",
    political_leaning: "Moderate",
    religion: "Catholic",
    top_concerns: ["economy", "fisheries", "outmigration"],
    commute_mode: "drives",
    estimated_annual_income: 45000,
    income_bracket: "$40K-$60K",
  },
  {
    uuid: "p-012",
    age: 26,
    sex: "Non-binary",
    occupation: "Graphic Designer",
    education_level: "Bachelor's degree",
    marital_status: "Never married",
    planning_area: "Montreal",
    province: "Quebec",
    immigration_status: "Canadian-born",
    indigenous_identity: "Non-Indigenous",
    visible_minority: "Not a visible minority",
    languages_spoken: "French, English",
    housing: "Renter, Apartment",
    cultural_background: "Québécois, artistic Mile End community",
    political_leaning: "Left",
    religion: "No religion",
    top_concerns: ["climate change", "arts funding", "housing affordability"],
    commute_mode: "cycles",
    estimated_annual_income: 42000,
    income_bracket: "$40K-$60K",
  },
];

const MOCK_REACTIONS_R1: Omit<Reaction, "persona">[] = [
  { reaction: "Hmm, this feels very Toronto-centric. In Quebec we think about these things differently — where's the French? This won't land here without bilingual effort.", sentiment_score: 4, resonates: false, tone_fit: "off", cultural_flags: ["no French", "Anglo-centric framing"] },
  { reaction: "The message is clean and direct, I appreciate that. But 'Canadian dream' feels outdated — most of my peers are worried about affording rent, not dreams.", sentiment_score: 5, resonates: false, tone_fit: "acceptable", cultural_flags: ["housing crisis tone-deaf"] },
  { reaction: "I've seen messaging like this before and it feels corporate. Real Canadians are struggling with healthcare wait times. Address that and you'll get my attention.", sentiment_score: 4, resonates: false, tone_fit: "acceptable", cultural_flags: ["healthcare gap"] },
  { reaction: "As a healthcare worker, the optimistic tone feels disconnected from reality. We're burned out. Acknowledge the struggle before selling hope.", sentiment_score: 3, resonates: false, tone_fit: "off", cultural_flags: ["healthcare burnout", "toxic positivity"] },
  { reaction: "This doesn't speak to Indigenous peoples at all. Our concerns are land rights, clean water, and reconciliation — not whatever this is marketing.", sentiment_score: 2, resonates: false, tone_fit: "off", cultural_flags: ["Indigenous erasure", "no reconciliation mention"] },
  { reaction: "Straightforward message. Doesn't bother me but doesn't excite me either. Out here we care about practical things — prices, jobs, keeping the farm going.", sentiment_score: 5, resonates: false, tone_fit: "acceptable", cultural_flags: [] },
  { reaction: "I like the energy but it feels like it's talking AT me, not WITH me. And there's no mention of diversity — Canada's strength IS its diversity.", sentiment_score: 5, resonates: false, tone_fit: "acceptable", cultural_flags: ["lacks diversity mention"] },
  { reaction: "Sounds like something from a politician's playbook. As someone in the oil patch, I want to hear about real economic plans, not buzzwords.", sentiment_score: 4, resonates: false, tone_fit: "off", cultural_flags: ["political buzzwords", "no energy sector"] },
  { reaction: "The concept is okay but it doesn't reflect the cost-of-living crisis. I work full-time and can barely afford a studio in Vancouver. Get real.", sentiment_score: 3, resonates: false, tone_fit: "off", cultural_flags: ["cost of living crisis", "housing"] },
  { reaction: "It's a nice sentiment but feels surface-level. I work with families who are really struggling. The message needs more empathy and less cheerfulness.", sentiment_score: 4, resonates: false, tone_fit: "acceptable", cultural_flags: ["lacks empathy depth"] },
  { reaction: "By, this is right mainland stuff. Nobody out here talks like that. Give us something that sounds like it knows the bay exists, would ya?", sentiment_score: 3, resonates: false, tone_fit: "off", cultural_flags: ["urban-centric", "ignores Atlantic Canada"] },
  { reaction: "C'est trop corporate, ça manque d'authenticité. Et pourquoi tout est juste en anglais? Le Québec existe, non?", sentiment_score: 3, resonates: false, tone_fit: "off", cultural_flags: ["English-only", "lacks authenticity"] },
];

const MOCK_REACTIONS_R2: Omit<Reaction, "persona">[] = [
  { reaction: "Ah, maintenant on parle! The bilingual approach shows respect. The acknowledgment of regional differences — that's more like it. Je suis plus réceptif.", sentiment_score: 7, resonates: true, tone_fit: "acceptable", cultural_flags: [] },
  { reaction: "Much better. Acknowledging that things are tough but focusing on what communities are doing — that feels honest. Still could address housing directly.", sentiment_score: 7, resonates: true, tone_fit: "acceptable", cultural_flags: [] },
  { reaction: "This version feels more grounded. Mentioning healthcare challenges directly instead of glossing over them. I'd actually read past the first line.", sentiment_score: 7, resonates: true, tone_fit: "perfect", cultural_flags: [] },
  { reaction: "Thank you for acknowledging the burnout. The shift from 'everything is great' to 'we see you' is powerful. This would actually land with my colleagues.", sentiment_score: 8, resonates: true, tone_fit: "perfect", cultural_flags: [] },
  { reaction: "Better — there's a reconciliation mention and it doesn't feel like an afterthought. The tone is more respectful. Still not perfect, but I'd engage with this.", sentiment_score: 6, resonates: true, tone_fit: "acceptable", cultural_flags: ["reconciliation could go deeper"] },
  { reaction: "Now you're talking sense. Mentioning local economies and practical realities. This is the kind of message I'd share at the co-op.", sentiment_score: 7, resonates: true, tone_fit: "perfect", cultural_flags: [] },
  { reaction: "Love this version! It celebrates diversity without being preachy. Feels like it was written by someone who actually lives in a diverse neighbourhood.", sentiment_score: 8, resonates: true, tone_fit: "perfect", cultural_flags: [] },
  { reaction: "Still a bit polished but at least it mentions the energy transition honestly. I don't feel talked down to anymore. That's progress.", sentiment_score: 6, resonates: true, tone_fit: "acceptable", cultural_flags: [] },
  { reaction: "The cost-of-living acknowledgment makes it real. Before it felt like an ad, now it feels like a conversation. Still needs more specifics.", sentiment_score: 7, resonates: true, tone_fit: "acceptable", cultural_flags: [] },
  { reaction: "This version has empathy. The stories about real families and communities — that resonates with the work I do every day. Well done.", sentiment_score: 8, resonates: true, tone_fit: "perfect", cultural_flags: [] },
  { reaction: "Now that's more like it, b'y! Mention of coastal communities and the fishery — someone actually thought about us. I'd share this one.", sentiment_score: 7, resonates: true, tone_fit: "acceptable", cultural_flags: [] },
  { reaction: "L'approche bilingue montre du respect. Le ton est plus authentique. C'est pas parfait, mais au moins on sent que le Québec fait partie de la conversation.", sentiment_score: 7, resonates: true, tone_fit: "acceptable", cultural_flags: [] },
];

export const MOCK_R1_AGGREGATE: AggregatedResults = {
  avg_sentiment: 3.75,
  resonance_pct: 0,
  tone_distribution: { perfect: 0, acceptable: 50, off: 50, offensive: 0 },
  top_cultural_flags: [
    "English-only / no French",
    "Urban-centric, ignores rural/Atlantic Canada",
    "Housing & cost-of-living crisis unaddressed",
    "Indigenous erasure / no reconciliation",
    "Healthcare burnout dismissed",
  ],
};

export const MOCK_OPTIMIZED: OptimizedMessage = {
  improved_message:
    "From coast to coast to coast — du littoral au littoral — Canadians are showing what resilience looks like. Not the glossy kind. The real kind: healthcare workers holding the line despite burnout, young families finding creative ways to build community despite the housing crunch, Indigenous communities leading reconciliation with strength, Prairie towns reinventing local economies, and Atlantic communities proving that smaller doesn't mean lesser. Canada isn't a dream — it's the work we do together, every day, in both official languages and hundreds more.",
  changes_made: [
    "Added bilingual elements (French phrases) for Quebec inclusion",
    "Replaced 'Canadian dream' with grounded, real-world framing",
    "Acknowledged healthcare burnout directly instead of toxic positivity",
    "Included explicit Indigenous reconciliation reference",
    "Referenced housing affordability and cost-of-living challenges",
    "Added regional specificity: Prairies, Atlantic, coastal communities",
    "Shifted tone from corporate to conversational and empathetic",
  ],
};

export const MOCK_R2_AGGREGATE: AggregatedResults = {
  avg_sentiment: 7.08,
  resonance_pct: 100,
  tone_distribution: { perfect: 42, acceptable: 58, off: 0, offensive: 0 },
  top_cultural_flags: ["reconciliation could go deeper"],
};

export function buildMockReactions(
  panel: Persona[],
  round: 1 | 2
): Reaction[] {
  const templates = round === 1 ? MOCK_REACTIONS_R1 : MOCK_REACTIONS_R2;
  return panel.map((persona, i) => ({
    persona,
    ...templates[i % templates.length],
    model_used: ["gpt-5-nano", "gemini-3-flash", "deepseek-v3.2", "mistral-small", "grok-3-mini"][i % 5],
  }));
}
